### ISSUE TITLE
Not work on android N

### ISSUE THREAD

**Issue by ghost** [rehacktive/waspdb#7]
`ERROR on readFromDisk: can't find /storage/emulated/0/Android/data/com.test.test/files/A938BF7A61BDC929C2225A8FEA52DBCE/salt
 at net.rehacktive.waspdb.internals.collision.KryoStoreUtils.readFromDisk(KryoStoreUtils.java:81)
 at net.rehacktive.waspdb.WaspFactory.loadDatabase(WaspFactory.java:164)
 at net.rehacktive.waspdb.WaspFactory$1.doInBackground(WaspFactory.java:33)
 at net.rehacktive.waspdb.WaspFactory$1.doInBackground(WaspFactory.java:26)
 at android.os.AsyncTask$2.call(AsyncTask.java:304)
 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
 at java.lang.Thread.run(Thread.java:761)`

**Comment by rehacktive** [comment]
Hi, thanks for the logcat.
Can you confirm the database was already created?
Do you mind posting also your code?

**Comment by rehacktive** [comment]
OK, I've found the problem, totally related to Android N.
working on a solution.

**Comment by rehacktive** [comment]
I've solved the issue on the new version 1.1
Please be sure you change your build.gradle with the new version:

compile 'com.github.rehacktive:waspdb:1.1'
